name: Build Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Build Release
      run: |
        ./gradlew assembleRelease
    - name: Store generated APK files
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: ./dragonide/build/outputs/apk/release/dragonide-release-unsigned.apk

